### PR TITLE
Fix for jira-python module rename

### PR DESCRIPTION
**Pull request by toabctl**
The python modules python-jira was renamed to jira.
Require the new module and also fix some possible naming
conflicts due to the rename.

### CODE REVIEW

**Comment by Loki22** [comment]
Hi Thomas,

I just gave the changes in the jira-rename branch a try and it's running into a similar NameError I was getting before which is why I added the two 'global' lines. Without making args and jira global, this error occurs when using an argument such as --issue-search-by-filter since it calls a function external to main().  But using an argument like --project-list will work just fine since the call to jira is local to main().  Here's the error output when using --issue-search-by-filter:

Traceback (most recent call last):
  File "bin/jiracli", line 10, in <module>
    sys.exit(main())
  File "/Users/xxx/python/envs/jiratest/lib/python2.7/site-packages/jiracli/__init__.py", line 554, in main
    issue_search_result_print(searchstring_list)
  File "/Users/xxx/python/envs/jiratest/lib/python2.7/site-packages/jiracli/__init__.py", line 252, in issue_search_result_print
    issues = jira_obj.search_issues(searchstr)
NameError: global name 'jira_obj' is not defined

**Comment by toabctl** [comment]
@Loki22 Ahh. Ok. I'll fix it. I'll merge this PR and then create another one to fix the problem you described. Thanks for the help!

**Comment by toabctl** [comment]
@Loki22 Does https://github.com/toabctl/jiracli/pull/12 solve your problem?

**Comment by toabctl** [comment]
@Loki22 I tested it with Puppetlabs Jira instance. Works for me.

**Comment by Loki22** [comment]
@toabctl I just tested out #12 and I think that fixed it. I tested issue-search-by-filter and it works fine. I see you're passing the object itself on each of the external function calls, I agree that's better than making the object global.  Awesome and thanks for the quick fix!

**Pull request merged**
